# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/data/bchenba/OQSORT/build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/data/bchenba/OQSORT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/data/bchenba/OQSORT/CMakeFiles /home/data/bchenba/OQSORT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/data/bchenba/OQSORT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

DataStore.o: DataStore.cpp.o
.PHONY : DataStore.o

# target to build an object file
DataStore.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DataStore.cpp.o
.PHONY : DataStore.cpp.o

DataStore.i: DataStore.cpp.i
.PHONY : DataStore.i

# target to preprocess a source file
DataStore.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DataStore.cpp.i
.PHONY : DataStore.cpp.i

DataStore.s: DataStore.cpp.s
.PHONY : DataStore.s

# target to generate assembly for a file
DataStore.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DataStore.cpp.s
.PHONY : DataStore.cpp.s

bitonic.o: bitonic.cpp.o
.PHONY : bitonic.o

# target to build an object file
bitonic.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bitonic.cpp.o
.PHONY : bitonic.cpp.o

bitonic.i: bitonic.cpp.i
.PHONY : bitonic.i

# target to preprocess a source file
bitonic.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bitonic.cpp.i
.PHONY : bitonic.cpp.i

bitonic.s: bitonic.cpp.s
.PHONY : bitonic.s

# target to generate assembly for a file
bitonic.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bitonic.cpp.s
.PHONY : bitonic.cpp.s

bucket.o: bucket.cpp.o
.PHONY : bucket.o

# target to build an object file
bucket.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bucket.cpp.o
.PHONY : bucket.cpp.o

bucket.i: bucket.cpp.i
.PHONY : bucket.i

# target to preprocess a source file
bucket.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bucket.cpp.i
.PHONY : bucket.cpp.i

bucket.s: bucket.cpp.s
.PHONY : bucket.s

# target to generate assembly for a file
bucket.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bucket.cpp.s
.PHONY : bucket.cpp.s

common.o: common.cpp.o
.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i
.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s
.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/common.cpp.s
.PHONY : common.cpp.s

enc.o: enc.cpp.o
.PHONY : enc.o

# target to build an object file
enc.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/enc.cpp.o
.PHONY : enc.cpp.o

enc.i: enc.cpp.i
.PHONY : enc.i

# target to preprocess a source file
enc.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/enc.cpp.i
.PHONY : enc.cpp.i

enc.s: enc.cpp.s
.PHONY : enc.s

# target to generate assembly for a file
enc.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/enc.cpp.s
.PHONY : enc.cpp.s

host.o: host.cpp.o
.PHONY : host.o

# target to build an object file
host.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/host.cpp.o
.PHONY : host.cpp.o

host.i: host.cpp.i
.PHONY : host.i

# target to preprocess a source file
host.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/host.cpp.i
.PHONY : host.cpp.i

host.s: host.cpp.s
.PHONY : host.s

# target to generate assembly for a file
host.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/host.cpp.s
.PHONY : host.cpp.s

oq.o: oq.cpp.o
.PHONY : oq.o

# target to build an object file
oq.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/oq.cpp.o
.PHONY : oq.cpp.o

oq.i: oq.cpp.i
.PHONY : oq.i

# target to preprocess a source file
oq.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/oq.cpp.i
.PHONY : oq.cpp.i

oq.s: oq.cpp.s
.PHONY : oq.s

# target to generate assembly for a file
oq.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/oq.cpp.s
.PHONY : oq.cpp.s

quick.o: quick.cpp.o
.PHONY : quick.o

# target to build an object file
quick.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/quick.cpp.o
.PHONY : quick.cpp.o

quick.i: quick.cpp.i
.PHONY : quick.i

# target to preprocess a source file
quick.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/quick.cpp.i
.PHONY : quick.cpp.i

quick.s: quick.cpp.s
.PHONY : quick.s

# target to generate assembly for a file
quick.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/quick.cpp.s
.PHONY : quick.cpp.s

shared.o: shared.cpp.o
.PHONY : shared.o

# target to build an object file
shared.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shared.cpp.o
.PHONY : shared.cpp.o

shared.i: shared.cpp.i
.PHONY : shared.i

# target to preprocess a source file
shared.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shared.cpp.i
.PHONY : shared.cpp.i

shared.s: shared.cpp.s
.PHONY : shared.s

# target to generate assembly for a file
shared.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shared.cpp.s
.PHONY : shared.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... DataStore.o"
	@echo "... DataStore.i"
	@echo "... DataStore.s"
	@echo "... bitonic.o"
	@echo "... bitonic.i"
	@echo "... bitonic.s"
	@echo "... bucket.o"
	@echo "... bucket.i"
	@echo "... bucket.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... enc.o"
	@echo "... enc.i"
	@echo "... enc.s"
	@echo "... host.o"
	@echo "... host.i"
	@echo "... host.s"
	@echo "... oq.o"
	@echo "... oq.i"
	@echo "... oq.s"
	@echo "... quick.o"
	@echo "... quick.i"
	@echo "... quick.s"
	@echo "... shared.o"
	@echo "... shared.i"
	@echo "... shared.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

