/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_HELLO_U_H
#define EDGER8R_HELLO_U_H

#include <openenclave/host.h>

#include "hello_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_hello_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t enclave_hello(
    oe_enclave_t* enclave,
    oe_result_t* _retval,
    char* this_is_a_string);

/**** OCALL prototypes. ****/
oe_result_t host_hello(char* this_is_a_string);

OE_EXTERNC_END

#endif // EDGER8R_HELLO_U_H
