/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "hello_u.h"

#include <openenclave/edger8r/host.h>

OE_EXTERNC_BEGIN

/**** Trusted function IDs. ****/
enum
{
    hello_fcn_id_enclave_hello = 0,
    hello_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** Trusted function names. ****/
static const oe_ecall_info_t _hello_ecall_info_table[] = 
{
    { "enclave_hello" },
};

/**** ECALL marshalling structs. ****/
typedef struct _enclave_hello_args_t
{
    oe_result_t oe_result;
    uint8_t* deepcopy_out_buffer;
    size_t deepcopy_out_buffer_size;
    oe_result_t oe_retval;
    char* this_is_a_string;
} enclave_hello_args_t;

/**** ECALL function wrappers. ****/

oe_result_t hello_enclave_hello(
    oe_enclave_t* enclave,
    oe_result_t* _retval,
    char* this_is_a_string)
{
    oe_result_t _result = OE_FAILURE;

    static uint64_t global_id = OE_GLOBAL_ECALL_ID_NULL;

    /* Marshalling struct. */
    enclave_hello_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;
    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.this_is_a_string = this_is_a_string;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(enclave_hello_args_t));
    /* There were no corresponding parameters. */
    
    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(enclave_hello_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)oe_malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (enclave_hello_args_t*)_input_buffer;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    /* There were no in nor in-out parameters. */
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function. */
    if ((_result = oe_call_enclave_function(
             enclave,
             &global_id,
             _hello_ecall_info_table[hello_fcn_id_enclave_hello].name,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size,
             &_output_bytes_written)) != OE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (enclave_hello_args_t*)_output_buffer;
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Check if the call succeeded. */
    if ((_result = _pargs_out->oe_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written. */
    if (_output_bytes_written != _output_buffer_size)
    {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->oe_retval;

    /* There were no out nor in-out parameters. */

    _result = OE_OK;

done:
    if (_buffer)
        oe_free(_buffer);

    return _result;
}

OE_WEAK_ALIAS(hello_enclave_hello, enclave_hello);

/**** Untrusted function IDs. ****/
enum
{
    hello_fcn_id_host_hello = 0,
    hello_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

/**** OCALL marshalling structs. ****/
typedef struct _host_hello_args_t
{
    oe_result_t oe_result;
    uint8_t* deepcopy_out_buffer;
    size_t deepcopy_out_buffer_size;
    oe_result_t oe_retval;
    char* this_is_a_string;
} host_hello_args_t;

/**** OCALL functions. ****/

static void ocall_host_hello(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;
    OE_UNUSED(input_buffer_size);

    /* Prepare parameters. */
    host_hello_args_t* _pargs_in = (host_hello_args_t*)input_buffer;
    host_hello_args_t* _pargs_out = (host_hello_args_t*)output_buffer;

    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    if (input_buffer_size < sizeof(*_pargs_in) || output_buffer_size < sizeof(*_pargs_in))
        goto done;

    /* Make sure input and output buffers are valid. */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;
    }

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Call user function. */
    _pargs_out->oe_retval = host_hello(
        _pargs_in->this_is_a_string);

    /* There is no deep-copyable out parameter. */
    _pargs_out->deepcopy_out_buffer = NULL;
    _pargs_out->deepcopy_out_buffer_size = 0;

    /* Propagate errno back to enclave. */
    /* Errno propagation not enabled. */

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = _output_buffer_offset;

done:
    if (_pargs_out && output_buffer_size >= sizeof(*_pargs_out))
        _pargs_out->oe_result = _result;
}

/**** OCALL function table. ****/

static oe_ocall_func_t _hello_ocall_function_table[] = {
    (oe_ocall_func_t) ocall_host_hello,
    NULL
};

oe_result_t oe_create_hello_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave)
{
    return oe_create_enclave(
               path,
               type,
               flags,
               settings,
               setting_count,
               _hello_ocall_function_table,
               1,
               _hello_ecall_info_table,
                1,
               enclave);
}

OE_EXTERNC_END
