/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_HELLO_T_H
#define EDGER8R_HELLO_T_H

#include <openenclave/enclave.h>

#include "hello_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
oe_result_t enclave_hello(char* this_is_a_string);

/**** OCALL prototypes. ****/
oe_result_t host_hello(
    oe_result_t* _retval,
    char* this_is_a_string);

OE_EXTERNC_END

#endif // EDGER8R_HELLO_T_H
