/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "hello_t.h"

#include <openenclave/edger8r/enclave.h>

OE_EXTERNC_BEGIN

/**** Trusted function IDs ****/
enum
{
    hello_fcn_id_enclave_hello = 0,
    hello_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** ECALL marshalling structs. ****/
typedef struct _enclave_hello_args_t
{
    oe_result_t oe_result;
    uint8_t* deepcopy_out_buffer;
    size_t deepcopy_out_buffer_size;
    oe_result_t oe_retval;
    char* this_is_a_string;
} enclave_hello_args_t;

/**** ECALL functions. ****/

static void ecall_enclave_hello(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_hello_args_t* _pargs_in = (enclave_hello_args_t*)input_buffer;
    enclave_hello_args_t* _pargs_out = (enclave_hello_args_t*)output_buffer;

    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    if (input_buffer_size < sizeof(*_pargs_in) || output_buffer_size < sizeof(*_pargs_in))
        goto done;

    /* Make sure input and output buffers lie within the enclave. */
    /* oe_is_within_enclave explicitly checks if buffers are null or not. */
    if (!oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    /* There were no in nor in-out parameters. */

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    /* There were no out nor in-out parameters. */

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    _pargs_out->oe_retval = enclave_hello(
        _pargs_in->this_is_a_string);

    /* There is no deep-copyable out parameter. */
    _pargs_out->deepcopy_out_buffer = NULL;
    _pargs_out->deepcopy_out_buffer_size = 0;

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = _output_buffer_offset;

done:
    if (output_buffer_size >= sizeof(*_pargs_out) &&
        oe_is_within_enclave(_pargs_out, output_buffer_size))
        _pargs_out->oe_result = _result;
}

/**** ECALL function table. ****/

oe_ecall_func_t oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_enclave_hello
};

size_t oe_ecalls_table_size = OE_COUNTOF(oe_ecalls_table);

/**** Untrusted function IDs. ****/
enum
{
    hello_fcn_id_host_hello = 0,
    hello_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

/**** OCALL marshalling structs. ****/
typedef struct _host_hello_args_t
{
    oe_result_t oe_result;
    uint8_t* deepcopy_out_buffer;
    size_t deepcopy_out_buffer_size;
    oe_result_t oe_retval;
    char* this_is_a_string;
} host_hello_args_t;

/**** OCALL function wrappers. ****/

oe_result_t host_hello(
    oe_result_t* _retval,
    char* this_is_a_string)
{
    oe_result_t _result = OE_FAILURE;

    /* If the enclave is in crashing/crashed status, new OCALL should fail
       immediately. */
    if (oe_get_enclave_status() != OE_OK)
        return oe_get_enclave_status();

    /* Marshalling struct. */
    host_hello_args_t _args, *_pargs_in = NULL, *_pargs_out = NULL;
    /* Marshalling buffer and sizes. */
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshalling struct. */
    memset(&_args, 0, sizeof(_args));
    _args.this_is_a_string = this_is_a_string;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(host_hello_args_t));
    /* There were no corresponding parameters. */
    
    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(host_hello_args_t));
    /* There were no corresponding parameters. */
    
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)oe_allocate_ocall_buffer(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }
    
    /* Serialize buffer inputs (in and in-out parameters). */
    _pargs_in = (host_hello_args_t*)_input_buffer;
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));
    /* There were no in nor in-out parameters. */
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call host function. */
    if ((_result = oe_call_host_function(
             hello_fcn_id_host_hello,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size,
             &_output_bytes_written)) != OE_OK)
        goto done;

    /* Setup output arg struct pointer. */
    _pargs_out = (host_hello_args_t*)_output_buffer;
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));
    
    /* Check if the call succeeded. */
    if ((_result = _pargs_out->oe_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written. */
    if (_output_bytes_written != _output_buffer_size)
    {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters. */
    *_retval = _pargs_out->oe_retval;

    /* There were no out nor in-out parameters. */

    /* Retrieve propagated errno from OCALL. */
    /* Errno propagation not enabled. */

    _result = OE_OK;

done:
    if (_buffer)
        oe_free_ocall_buffer(_buffer);

    return _result;
}

OE_EXTERNC_END
